### ISSUE TITLE
java.lang.NumberFormatException: For input string: "HNL"

### ISSUE THREAD

**Issue by Blackmorse** [Blackmorse/hat-all-stats#219]
Oct 08 05:21:13 ge-r610 sbt[1430267]: java.lang.NumberFormatException: For input string: "HNL"
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at java.base/java.lang.Integer.parseInt(Integer.java:652)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at java.base/java.lang.Integer.parseInt(Integer.java:770)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at scala.collection.immutable.StringLike.toInt(StringLike.scala:304)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at scala.collection.immutable.StringLike.toInt$(StringLike.scala:304)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at scala.collection.immutable.StringOps.toInt(StringOps.scala:33)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at utils.LeagueNameParser$.getLeagueUnitNumberByName(LeagueNameParser.scala:7)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at views.html.common.teamRanking$.apply(teamRanking.template.scala:112)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at views.html.team.teamOverview$.apply(teamOverview.template.scala:106)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at controllers.TeamController.$anonfun$teamOverview$13(TeamController.scala:81)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at scala.util.Success.$anonfun$map$1(Try.scala:255)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at scala.util.Success.map(Try.scala:213)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
Oct 08 05:21:13 ge-r610 sbt[1430267]:         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by Blackmorse** [comment]
Already fixed
